import Head from 'next/head'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>MovieDB</title>
                <link rel="icon" href="../static/favicon.png" />
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Component {...pageProps} />
        </>
    )
}

export default MyApp
